.TH PHMENU 1 "November 2008" "phmenu Version 1.01"
.SH NAME
phmenu \- Menu for Dominion Employee Telephone Listings
.SH SYNOPSIS
\fB phmenu\fP
.SH DESCRIPTION
\fP Menu for maintaining employees' phones and job titles\fP.
\fP Record includes phone number, name, dept, and date-hired\fP.
.SS Options
.TP
\fB -v \fIView Phone List\fR
Display unformatted phone records.
.TP
\fB -p \fIPrint Phone List\fR
Corporate Phones report sorted by Employee Name.
.TP
\fB -a \fIAdd Phone to List\fR
Add new phone record.
.TP
\fB -p \fIPrint Phone List\fR
Enter Name to search and retreive phone record.
.TP
\fB -d \dIDelete Phone\fR
Remove phone record.
.SH FILES
.TP
\fC/home/Chapter6/source/corp_phones\fR
